apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        app: cbz-app
    spec: 
      containers:
        - name: my-pod-cont
          image: nginx
          ports:
            - name: apiVersion: autoscaling/v2
            kind: HorizontalPodAutoscaler
            metadata:
              name: myapp
            spec:
              scaleTargetRef:
                apiVersion: apps/v1
                kind: Deployment
                name: myapp
              minReplicas: 1
              maxReplicas: 3
              metrics:
              - type: Resource
                resource:
                  name: cpu
                  target:
                    type: Utilization
                    averageUtilization: 50
            
