apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-rs
spec:
  replicas: 3
  selector:
    matchExpressions:
    - {key: app, operator: In, values: [my-xyz, cbz-app]}
  template: 
    metadata:
      labels:
        app: cbz-app
    spec: 
      containers:
      - name: my-pod-cont
        image: nginx
        ports:
        - name: http 
          containerPort: 80
          protocol: TCP